// build-host 防回归：产物 host.js 里的跨包依赖必须是「外部化裸说明符」，而不是被内联。
//
// 为什么值得一条测试（两个坏方向都不报错、只在线上发作）：发布形态下 host.js 躺在
// node_modules 里被 dsh 载入——
//   1) 内联：`@jayyuen66/dsh-plugin-shared/lib/http` 这类**子路径**说明符一旦被打进产物，shared 的
//      模块级状态就在每个插件里各复制一份；rolldown 的 external 字符串项是精确匹配，
//      只列包名会漏掉子路径，故 build-host.mjs 按「包名段」判定（该坑已在脚本注释登记）。
//   2) 残留：产物里只要还剩 `./lib/xxx.ts`，Node 载入即抛 ERR_UNSUPPORTED_NODE_MODULES_
//      TYPE_STRIPPING；而 dependencies 里跑掉一个包（如 schemastery 退回 devDependencies）
//      就会被整包内联——体积翻倍正是内联发生了的指纹，故一并钉住。
import { describe, it } from "vitest";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { buildHost } from "../build-host.mjs";
import { hostFreshnessEvidence } from "./host-freshness.ts";

describe("buildHost()", () => {
  it("host.js 与最新构建逐字节一致（改 host.ts / lib/*.ts 后必须 node build-host.mjs）", async () => {
    const { pkgName, pkgDir, onDisk, built } = await hostFreshnessEvidence(import.meta.url);
    assert.equal(
      onDisk,
      built,
      onDisk === built
        ? "fresh"
        : `[${pkgName}] host.js 已过期：host.ts（或其依赖）变更后未重建。请运行：cd ${pkgDir} && node build-host.mjs`,
    );
  });

  it("产物 host.js：运行期跨包依赖保持 external（未内联）", async () => {
    const out = await buildHost();
    assert.ok(
      out.startsWith("// GENERATED by build-host.mjs"),
      "产物须带生成标记（勿手改 host.js）",
    );
    // 值导入的包必须列在 dependencies，否则被内联。0.1.7 起这个值导入是**宿主 fork**
    // 的 schemastery：只有它的 resolve 会把 .volatile() 字段包成 Volatile 引用，
    // 公共 schemastery 既没有 .volatile()、解析出的也仍是普通值（设置卡写的值读不到）。
    assert.ok(
      out.includes('from "@deepseek-ai/schemastery"'),
      "@deepseek-ai/schemastery 必须以裸说明符形式留在产物里",
    );
    // 反向锁：不得退回公共 schemastery（fork 缺失时 .volatile() 直接 TypeError，
    // 而即便装上了，两份 schemastery 单例也会让宿主的 volatileForm 判据对不上号）。
    assert.ok(
      !/from\s+["']schemastery["']/u.test(out),
      "host.js 不得再值导入公共 schemastery（0.1.7 volatile 解析只在宿主 fork 里）",
    );
    // 子路径说明符：external 字符串项匹配不到的那个坑。**逐个说明符**列名——只查
    // `@jayyuen66/dsh-plugin-shared/` 前缀会被 http 一条满足，看不见新接进来的
    // lib/text（终审指出的 Minor：那种断言对"某个子路径被内联"是瞎的）。
    for (const subpath of [
      "lib/http",
      "lib/locale",
      "lib/text",
      "lib/record",
      "lib/errors",
      "lib/job-outcome",
    ]) {
      assert.ok(
        out.includes(`from "@jayyuen66/dsh-plugin-shared/${subpath}"`),
        `shared/${subpath} 必须外部化（裸说明符形式留在产物里）`,
      );
    }
    // 自有 lib/cli.ts 的转义器要"在产物内"（内联成功）而不是留成相对说明符
    assert.ok(out.includes("shq"), "lib/cli.ts 须已并入单文件产物");
  });

  it("产物 host.js：不残留 ./x.ts 形态的相对说明符", async () => {
    const out = await buildHost();
    // lib/*.ts 应已被吃进单文件；留着即"发布后 Node 直接拒载"的形态
    assert.ok(!/["']\.\/[^"']*\.ts["']/u.test(out), "不得有 ./x.ts 说明符残留");
  });
});

describe("闸门的外部化面（shared/lib/trust）", () => {
  it("lib/trust 子路径保持裸说明符，且 guardTrust 的实现未被内联", async () => {
    // 这些包原先只钉了 http/project-key/record/jsonl 几枚子路径，`lib/trust` 是新增的第四个坑位：
    // external 的字符串项是精确匹配，子路径一旦漏掉就把整份判据复制进本包产物（判据分叉的起点）。
    const out = await buildHost();
    assert.ok(
      out.includes('from "@jayyuen66/dsh-plugin-shared/lib/trust"'),
      "shared/trust 必须外部化",
    );
    assert.ok(!/^function guardTrust\(/mu.test(out), "产物不得内联 guardTrust 的函数体");
  });
});

describe("换装的产物面（ctx.jobs 只有类型面）", () => {
  it("host.js 里不得出现 @deepseek-ai/dsh-jobs 的运行时说明符", async () => {
    const out = await buildHost();
    // 注册表那枚实例由宿主注入（dsh-base 默认装载 dsh-jobs-local），本包只借它的**类型**；
    // 一旦有人改成值导入，host.js 就多一条运行时跨包说明符——发布形态下那条说明符要能在
    // 消费方的 node_modules 里解析得到，而它只在 devDependencies 里。
    // 判据只看 `from "…"` 位置：源码注释会随 rolldown 一起进产物，整串匹配会被注释误伤
    // （第一版就是这么把自己判红的）。
    assert.ok(
      !/from\s*["']@deepseek-ai\/dsh-jobs/u.test(out),
      "dsh-jobs 只能是类型面：产物里出现它的运行时说明符即值导入",
    );
    assert.ok(
      !/from\s*["']@deepseek-ai\/dsh-jobs-local/u.test(out),
      "官方注册表的实现只允许出现在 test/，产物必须自包含",
    );
  });

  it("package.json：dsh-jobs 与 dsh-jobs-local 都只在 devDependencies", () => {
    const manifestPath = fileURLToPath(new URL("../package.json", import.meta.url));
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    // 两个槽位的理由不同，但结论一样：dsh-jobs 只提供 host.ts 的**类型**（注册表实例由
    // 宿主注入），dsh-jobs-local 只被 test/ 用来起真注册表（生产代码从不 import 它）。
    // 任何一枚进了 dependencies，发布包就会要求消费方装一个宿主本来就有的东西。
    for (const name of ["@deepseek-ai/dsh-jobs", "@deepseek-ai/dsh-jobs-local"]) {
      assert.equal(manifest.dependencies?.[name], undefined, `${name} 不该在 dependencies`);
      assert.notEqual(
        manifest.devDependencies?.[name],
        undefined,
        `${name} 必须在 devDependencies`,
      );
    }
  });
});
