#!/usr/bin/env node
/// <reference types="node" />
// 构建 host.js：rolldown 把 host.ts 及其 `./lib/*` 依赖打成单文件 ESM，落在**包根**
// （与源码同目录，故 `import.meta.dirname` 的语义与源码态完全一致）。
// 为什么必须有这一步：Node 对 node_modules 里的 .ts 直接抛
// ERR_UNSUPPORTED_NODE_MODULES_TYPE_STRIPPING（实测），而发布出去的包正是躺在
// node_modules 里被 dsh 载入的；官方示例包（docs/user/develop/basic/publish.zh.md
// 的 hello-plugin）也是包根放 index.js 产物。本仓 host.ts + client.js 同形态。
// 不产 .d.ts：插件包对外没有 TS API——dsh 按包名载入运行，没有人 import 它。
// 顶部 node reference：oxlint 类型检查对 .mjs 不自动加载 @types/node，需显式声明
// 才能解析 node:fs/promises、process、import.meta（否则整文件按 error 类型误报 unsafe）。
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { rolldown } from "rolldown";
import { canonicalizeRegionPaths } from "@jayyuen666/dsh-plugin-shared/lib/canonicalize-region-paths";

const root = import.meta.dirname;

/** @type {unknown} */
const pkgJson = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));

/**
 * 从 JSON.parse 的 unknown 投影为 Record（非对象 → 空对象兜底），避免 any 索引。
 * @param {unknown} raw
 * @returns {Record<string, unknown>}
 */
function asRecord(raw) {
  if (raw !== null && typeof raw === "object" && !Array.isArray(raw)) {
    return raw;
  }
  return {};
}

/**
 * 取依赖表里的包名清单（值即外部化说明符）。
 * @param {string} field
 * @returns {string[]}
 */
function dependencyNames(field) {
  const table = asRecord(asRecord(pkgJson)[field]);
  return Object.keys(table).filter((name) => typeof table[name] === "string");
}

// dependencies/peerDependencies 一律外部化：它们由 pnpm 真实安装，产物里保留裸
// 说明符才拿得到单例（内联会把 shared 的模块级状态复制成多份）。子路径说明符同样
// 要外部化——external 的字符串项是精确匹配，所以按「包名段」判定而不是枚举子路径。
const externalNames = new Set([
  ...dependencyNames("dependencies"),
  ...dependencyNames("peerDependencies"),
]);

/**
 * 说明符的包名段：`@scope/pkg/sub` → `@scope/pkg`，`pkg/sub` → `pkg`。
 * @param {string} id
 * @returns {string}
 */
function packageNameOf(id) {
  const segments = id.split("/");
  if (id.startsWith("@")) {
    return segments.slice(0, 2).join("/");
  }
  return segments[0] ?? id;
}

/**
 * rolldown 外部化判据。
 * @param {string} id
 * @returns {boolean}
 */
const isExternal = (id) => externalNames.has(packageNameOf(id));

/**
 * 生成 host.js 的完整文本。
 * @returns {Promise<string>}
 */
export async function buildHost() {
  const bundle = await rolldown({
    input: path.join(root, "host.ts"),
    external: isExternal,
    platform: "node",
    resolve: { extensions: [".ts", ".mjs", ".js"] },
  });
  const { output } = await bundle.generate({ format: "esm" });
  const chunk = output.find((item) => item.type === "chunk");
  if (chunk === undefined) {
    throw new Error("rolldown generate returned no chunk output");
  }
  // `//#region` 行的路径由 rolldown 按 process.cwd() 算出 ⇒ 同一份源码有两种字节（cwd=包根 写
  // `lib/x.ts`，cwd=plugins/ 写 `<包名>/lib/x.ts`）。折成 canonical 必须落在**返回值之前**：
  // test/host-freshness.ts 拿内存构建与磁盘产物逐字节比，只在一侧折就永远红。
  const code = canonicalizeRegionPaths(chunk.code.trimEnd(), root);
  return `// GENERATED by build-host.mjs — edit host.ts / lib/*.ts, then run \`node build-host.mjs\`.\n${code}\n`;
}

async function main() {
  const out = await buildHost();
  await writeFile(path.join(root, "host.js"), out, "utf8");
  console.info("host.js written:", out.length, "chars");
}

if (process.argv[1] === import.meta.filename) {
  try {
    await main();
  } catch (error) {
    console.error(error);
    process.exitCode = 1;
  }
}
